source 'http://ruby.taobao.org'
source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'grape'
gem 'datamapper', '>= 1.2.0'
gem 'dm-postgres-adapter'
gem 'dm-sqlite-adapter'
gem 'thin'
gem 'sinatra'
gem 'puma'
gem 'rainbows'
